<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="len103" name="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations" tests="21" failures="2" timestamp="25 Sep 2019 09:10:15 GMT" time="73.989" errors="0">
  <testcase name="chargeCodeNegativeScenario" time="2.788" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="2.691" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="2.699" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="3.420" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="4.254" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="2.823" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="2.691" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="5.924" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="3.375" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="4.334" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="2.745" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:expected [400] but found [500]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations.chargeCodeNegativeScenario(ControllerfortermloanchargecodesCRUDoperations.java:112)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- chargeCodeNegativeScenario -->
  <testcase name="chargeCodeNegativeScenario" time="2.629" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="3.261" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="2.883" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="6.544" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [502]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:expected [400] but found [502]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations.chargeCodeNegativeScenario(ControllerfortermloanchargecodesCRUDoperations.java:112)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- chargeCodeNegativeScenario -->
  <testcase name="chargeCodeNegativeScenario" time="3.306" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="2.943" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="6.075" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="2.729" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="3.209" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
  <testcase name="chargeCodeNegativeScenario" time="2.666" classname="com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations"/>
</testsuite> <!-- com.idexcel.termloanservice.scripts.ControllerfortermloanchargecodesCRUDoperations -->
