<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="len167" name="com.idexcel.financialanalyser.scripts.Financialanalyser" tests="48" failures="7" timestamp="12 Aug 2019 10:27:13 GMT" time="128.832" errors="0">
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.517" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.614" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.619" classname="com.idexcel.financialanalyser.scripts.Financialanalyser">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [404]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.idexcel.financialanalyser.scripts.Financialanalyser.FA_PositiveAndNegativeScenarios(Financialanalyser.java:140)
	at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- FA_PositiveAndNegativeScenarios -->
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.679" classname="com.idexcel.financialanalyser.scripts.Financialanalyser">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [404]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.idexcel.financialanalyser.scripts.Financialanalyser.FA_PositiveAndNegativeScenarios(Financialanalyser.java:140)
	at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- FA_PositiveAndNegativeScenarios -->
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.603" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.627" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.571" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.611" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.604" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.600" classname="com.idexcel.financialanalyser.scripts.Financialanalyser">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [404]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.idexcel.financialanalyser.scripts.Financialanalyser.FA_PositiveAndNegativeScenarios(Financialanalyser.java:140)
	at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- FA_PositiveAndNegativeScenarios -->
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.690" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.666" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.646" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.535" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="5.046" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.653" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.491" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.629" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.604" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.604" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.641" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.739" classname="com.idexcel.financialanalyser.scripts.Financialanalyser">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [404]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.idexcel.financialanalyser.scripts.Financialanalyser.FA_PositiveAndNegativeScenarios(Financialanalyser.java:140)
	at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- FA_PositiveAndNegativeScenarios -->
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.531" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.585" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.609" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.532" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.631" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.561" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.657" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.702" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.627" classname="com.idexcel.financialanalyser.scripts.Financialanalyser">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [404]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.idexcel.financialanalyser.scripts.Financialanalyser.FA_PositiveAndNegativeScenarios(Financialanalyser.java:140)
	at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- FA_PositiveAndNegativeScenarios -->
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.568" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.675" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.590" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.609" classname="com.idexcel.financialanalyser.scripts.Financialanalyser">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [404]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.idexcel.financialanalyser.scripts.Financialanalyser.FA_PositiveAndNegativeScenarios(Financialanalyser.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- FA_PositiveAndNegativeScenarios -->
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.542" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.609" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.693" classname="com.idexcel.financialanalyser.scripts.Financialanalyser">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [404]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.idexcel.financialanalyser.scripts.Financialanalyser.FA_PositiveAndNegativeScenarios(Financialanalyser.java:140)
	at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- FA_PositiveAndNegativeScenarios -->
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.659" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.603" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.619" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.543" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.598" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.590" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.626" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.682" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="3.489" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
  <testcase name="FA_PositiveAndNegativeScenarios" time="2.713" classname="com.idexcel.financialanalyser.scripts.Financialanalyser"/>
</testsuite> <!-- com.idexcel.financialanalyser.scripts.Financialanalyser -->
