<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="len103" name="com.idexcel.termloanservice.scripts.Chargecode" tests="46" failures="12" timestamp="23 Sep 2019 05:32:19 GMT" time="144.298" errors="0">
  <testcase name="termLoanAllGetmethods" time="2.714" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.762" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.868" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termloan" time="0.000" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <skipped/>
  </testcase> <!-- termloan -->
  <testcase name="termLoanAllGetmethods" time="2.635" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="lateFeePost" time="26.664" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [201] but found [400],
	expected [204] but found [400],
	expected [204] but found [404],
	expected [404] but found [200],
	expected [201] but found [400],
	expected [204] but found [400],
	expected [204] but found [404],
	expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:expected [201] but found [400],expected [204] but found [400],expected [204] but found [404],expected [404] but found [200],expected [201] but found [400],expected [204] but found [400],expected [204] but found [404],expected [404] but found [200]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.Chargecode.lateFeePost(Chargecode.java:380)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- lateFeePost -->
  <testcase name="ChargeTemplateEdit" time="3.165" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [204]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:expected [400] but found [204]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.Chargecode.ChargeTemplateEdit(Chargecode.java:339)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- ChargeTemplateEdit -->
  <testcase name="termLoanAllGetmethods" time="2.679" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanDelete" time="2.720" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [204] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:expected [204] but found [404]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.Chargecode.termLoanDelete(Chargecode.java:254)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- termLoanDelete -->
  <testcase name="termloan_FrequencyValidation" time="2.696" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="ChargeTemplateEdit" time="3.154" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="ChargeTemplateEdit" time="3.150" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [204]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:expected [400] but found [204]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.Chargecode.ChargeTemplateEdit(Chargecode.java:339)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- ChargeTemplateEdit -->
  <testcase name="termLoanAllGetmethods" time="2.625" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanEdit1" time="0.000" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <skipped/>
  </testcase> <!-- termLoanEdit1 -->
  <testcase name="termLoanAllGetmethods" time="2.661" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.783" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.681" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.653" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	get termloan API statusCode expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:get termloan API statusCode expected [200] but found [404]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.Chargecode.termLoanAllGetmethods(Chargecode.java:142)at sun.reflect.GeneratedMethodAccessor187.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- termLoanAllGetmethods -->
  <testcase name="ChargeTemplateEdit" time="3.748" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termloan_ChargetypesValidation" time="4.017" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.700" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.722" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="ProcessOneTimePost" time="0.000" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <skipped/>
  </testcase> <!-- ProcessOneTimePost -->
  <testcase name="termLoanAllGetmethods" time="2.666" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.639" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="ChargeTemplateDelete" time="2.702" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [204] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:expected [204] but found [404]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.Chargecode.ChargeTemplateDelete(Chargecode.java:317)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- ChargeTemplateDelete -->
  <testcase name="ChargeTemplateEdit" time="2.635" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="ChargeTemplateEdit" time="3.232" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.618" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="chargecodeCreation" time="0.000" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <skipped/>
  </testcase> <!-- chargecodeCreation -->
  <testcase name="AmortizationEdit" time="8.475" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.677" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.677" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.681" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	get termloan API statusCode expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:get termloan API statusCode expected [404] but found [200]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.Chargecode.termLoanAllGetmethods(Chargecode.java:142)at sun.reflect.GeneratedMethodAccessor187.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- termLoanAllGetmethods -->
  <testcase name="termLoanAllGetmethods" time="2.652" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.699" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	get termloan API statusCode expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:get termloan API statusCode expected [200] but found [404]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.Chargecode.termLoanAllGetmethods(Chargecode.java:142)at sun.reflect.GeneratedMethodAccessor187.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- termLoanAllGetmethods -->
  <testcase name="termLoanAllGetmethods" time="2.687" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termloan_NatSignValidation" time="2.729" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.608" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	get termloan API statusCode expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:get termloan API statusCode expected [200] but found [404]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.Chargecode.termLoanAllGetmethods(Chargecode.java:142)at sun.reflect.GeneratedMethodAccessor187.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- termLoanAllGetmethods -->
  <testcase name="termLoanAllGetmethods" time="2.634" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="chargecodeMoreTwentyfiveCharacter" time="0.000" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <skipped/>
  </testcase> <!-- chargecodeMoreTwentyfiveCharacter -->
  <testcase name="termLoanEdit" time="2.765" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected content-type &quot;JSON&quot; doesn&#039;t match actual content-type &quot;&quot;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.Expected content-type "JSON" doesn't match actual content-type "".at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.lang.reflect.Constructor.newInstance(Constructor.java:423)at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:471)at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:643)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)at io.restassured.internal.ResponseSpecificationImpl.contentType(ResponseSpecificationImpl.groovy:399)at io.restassured.internal.ValidatableResponseOptionsImpl.contentType(ValidatableResponseOptionsImpl.java:244)at com.idexcel.termloanservice.scripts.Chargecode.termLoanEdit(Chargecode.java:227)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- termLoanEdit -->
  <testcase name="termLoanAllGetmethods" time="2.664" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
  <testcase name="termLoanAllGetmethods" time="2.607" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	get termloan API statusCode expected [400] but found [404]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:get termloan API statusCode expected [400] but found [404]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.Chargecode.termLoanAllGetmethods(Chargecode.java:142)at sun.reflect.GeneratedMethodAccessor187.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- termLoanAllGetmethods -->
  <testcase name="ChargeTemplateAdd" time="2.728" classname="com.idexcel.termloanservice.scripts.Chargecode">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [201] but found [409]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:expected [201] but found [409]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.idexcel.termloanservice.scripts.Chargecode.ChargeTemplateAdd(Chargecode.java:297)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- ChargeTemplateAdd -->
  <testcase name="lateFeeUpdate" time="2.726" classname="com.idexcel.termloanservice.scripts.Chargecode"/>
</testsuite> <!-- com.idexcel.termloanservice.scripts.Chargecode -->
